name: CI

on:
  push:
    branches:
      - master
    tags:
      # Version tags.
      #
      # Tags matching this pattern will cause the "release" job below to run,
      # so edit it carefully!  It should not match arbitrary tags.
      - "[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
  workflow_dispatch:

  # Routinely check that we continue to work in the face of external changes.
  schedule:
    # Every day at 17:42 UTC / 9:42 Seattle (winter) / 10:42 Seattle (summer)
    - cron: "42 17 * * *"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  test-source:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  release:
    if: false
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  report-failure:
    if: ${{ always() && github.ref_name == github.event.repository.default_branch }}
    needs:
      - lint
      - test-source
      - release
    # FIXME: drop the branch tag after merging https://github.com/nextstrain/.github/pull/121
    uses: nextstrain/.github/.github/workflows/report-failure.yaml@victorlin/report-failure
    with:
      failure: ${{ contains(needs.*.result, 'failure') }}

      # The condition evaluates to true when all results are 'success',
      # 'cancelled', or 'skipped'ยน. This is not ideal, since a workflow that is
      # cancelled before there are any successes will still signal a success to
      # this job, however the chance of that happening should be very low given
      # that this is job is conditioned on the default branch.
      # ยน <https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#jobs-context>
      success: ${{ !contains(needs.*.result, 'failure') }}
      title: CI failure
    secrets:
      token: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT_REPO }}
